### ISSUE TITLE
looking for the code for the interact demo

### ISSUE THREAD

**Issue by happysalada** [braid-org/braidjs#13]
Hi,

    Very cool project!

    I really liked the interactive demo on https://braid.org/demo/interact
    I was looking for the code for it. In case it is available, I would be interested.

Thank you!

**Comment by toomim** [comment]
Hi happy!

Yes, we actually wrote this in a "classic" web programming style to make the source code accessible — it's embedded in the HTML file.

You'll want to click the "view fullscreen" button to go to https://braid.org/play, and then view source in your browser. The javascript is all there.

This file is portable. You can save it to disk, edit it directly, and open the page in your browser. There are no frameworks, there's no server-side compilation, none of that nonsense getting in the way.

**Comment by happysalada** [comment]
Thank you!
