### ISSUE TITLE
Incorrectly used parseInt

### ISSUE THREAD

**Issue by kof** [braid-org/braidjs#21]
I was just skimming through the codebase and saw parseInt used without a second argument. That's a bit alarming

https://github.com/braid-org/braidjs/blob/61ff73b1e1bea0019d17c197d714ece50dbfcce3/json-patch/apply-patch.js#L18

**Comment by toomim** [comment]
Thank you. Fixed in https://github.com/braid-org/braidjs/commit/7374fed7b9d02a110fa7ffc7ac5afeb05de51241
