### ISSUE TITLE
[Antimatter] Missing read_raw definition

### ISSUE THREAD

**Issue by canadaduane** [braid-org/braidjs#22]
Antimatter 520 seems to be missing the definition of the `read_raw` function.

https://github.com/braid-org/braidjs/blob/master/antimatter/antimatter.js#L1352

**Comment by toomim** [comment]
Ah, you're right! Greg confirms this is a bug and is looking into the fix.

**Comment by dglittle** [comment]
Thanks for pointing this out! It should now be fixed (also uploaded new npm module version 0.0.22 that has this fix)

**Comment by canadaduane** [comment]
Awesome, thanks!
