### ISSUE TITLE
Question about fissure and ack, continued

### ISSUE THREAD

**Issue by iacore** [braid-org/braidjs#27]
Let's say

1. a message is tagged with fissure
2. the author of the message goes offline 
3. fissure resolves

What happens now? Does the message stay in memory, never to be acknowledged?

**Comment by toomim** [comment]
When the author goes offline, that will create another fissure, which will freeze versions in memory like the first fissure did. Fissures replace each other like that; always marking when *some* necessary subnet is offline.

**Comment by iacore** [comment]
OK, I think I understand. Mind if I add Typescript annotation to antimatter.js?

**Comment by toomim** [comment]
Greg and I prefer Javascript to Typescript. However, I could imagine that some of your interest in adding types is to understand how the code fits together — to that end, I *do* want to make the code easier to understand, and would be happy to collaborate on doing so in Javascript.

**Comment by iacore** [comment]
Would a compromise to be using JSDoc to annotate types?

Move by svelte to switch from Typescript to JSDoc: https://github.com/sveltejs/svelte/pull/8569

Some form of a tutorial: https://dev.to/mirzaleka/learn-how-to-document-javascripttypescript-code-using-jsdoc-typedoc-359h
