### ISSUE TITLE
Publish as NPM package

### ISSUE THREAD

**Issue by canadaduane** [braid-org/braidjs#9]
The last update was 8 months ago. We should publish the latest braidjs package.

We're looking for the best way to expose the braid protocol API. Currently, I'm thinking of the following two functions:

1. `fetch`: (e.g. `import { fetch } from 'braidjs'`) This is the braid-augmented "whatwg fetch" that we provide, allowing HTTP subscriptions and patches among other things. It works in browser & in nodejs.
2. `braidify`: (e.g. `import { braidify } from 'braidjs'`) This is the braid middleware on the server side that can be used, e.g. in express or polka.

Also, we'd like to make the package both es6 and commonjs compatible, so we need to consider how to package and export these in a way that works for both module systems.

**Comment by postspectacular** [comment]
FWIW I've been keeping an eye on this project for a while now and would _love_ the new stuff packaged up so I can play around with a bit easier... Thanks for all your effort(s)! 👍

**Comment by canadaduane** [comment]
Done! https://www.npmjs.com/package/braidify
